### ISSUE TITLE
Feedback on experience

### ISSUE THREAD

**Issue by paulocoghi** [Conduitry/cheap-watch#1]
Hi, Conduitry!

I'd like to ask how your experience with cheap-watch has been about the possible problems and inconsistencies with the original Node.js implementation to watch files, that others libraries (like yours, [facebook](https://facebook.github.io/watchman/docs/nodejs.html) [watchman](https://www.npmjs.com/package/fb-watchman), [jung](https://github.com/jarofghosts/jung), [sane](https://github.com/amasad/sane), [gaze](https://github.com/shama/gaze), [chokidar](https://github.com/paulmillr/chokidar), [watch](https://github.com/mikeal/watch), [pathwatcher](https://github.com/atom/node-pathwatcher), [watchr](https://github.com/bevry/watchr), etc) are trying to solve.

[Many people](https://www.reddit.com/r/javascript/comments/91a3tp/why_is_there_no_small_sane_nodejs_tool_for/) need to know your library.

Has cheap-watch worked well, including on multiple operational systems?

I'm playing a little with cheap-watch and my main concern right now is about the possibility to inform multiple directories and also final files, instead of directories only.

Thanks for your attention!

**Comment by Conduitry** [comment]
Unless there are some secret users somewhere, the most serious workout that this library has gotten is almost certainly as the watcher bundled into Sapper. I haven't heard any complaints about its behavior there, or bugs in Sapper that sound like a failure in file watching.

I'm not sure what approach other libraries take for this, but what I'm doing is to take everything I hear from `fs.watch` with a large grain of salt, and perform my own calls to `fs.stat` to verify everything. Which files and directories to check comes from `fs.watch`, but every change event that the library returns has been verified using `fs.stat`. This has seemed to work quite well. There is a small suite of tests I was fiddling with a while ago, and I got them to pass on Travis-CI on linux, mac, and windows.

One other thing which has helped keep this library simple and small is the offloading of all globbing-related concerns. I've found there is a fair bit of complexity (some of which was related to cross-platform stuff) in other file watching libraries related to this - and that assuming the consumer knows how to write a callback (which is called with the relative path and the file's/directory's stats and which returns whether to watch it) made a lot of things simpler and more powerful.

It's hard to shake the feeling that the zillions of lines of code and dependencies in other watcher libraries must be for _something_ and aren't just entirely useless - but barring that I am quite comfortable and happy with this library. It's served Sapper well, and I'm a lot more comfortable with this minimal approach to this problem than I am with the behemoth that is pretty much any other file watching library.

**Comment by paulocoghi** [comment]
Wow! Your approach seems **really solid**. Also, being used by Sapper with no complains reinforces that.

From now on, cheap-watch will not only be used on Sapper, but on Alumna* as well (to be [properly released](https://github.com/alumna/alumna), previously named Altiva).

***About Alumna:** I talked with Rich Harris before about [a different way to manage components and routing](https://github.com/sveltejs/svelte/issues/1267#issuecomment-375099528) which I had created a few years ago, and which I believe makes more sense. As Sapper followed a different path, Alumna exists to fulfill the other option.

**Comment by paulocoghi** [comment]
Thanks a lot for your response! :)
