### ISSUE TITLE
Type 'typeof EventEmitter' is not a constructor function type.

### ISSUE THREAD

**Issue by jakobrosenberg** [Conduitry/cheap-watch#3]
When running ``tsc`` in a project folder with ``cheap-watch``
![image](https://user-images.githubusercontent.com/4153004/80304830-e8577780-87b8-11ea-81ed-1af3d089d64d.png)

**Comment by ryanatkn** [comment]
Added a fix in #4. I think you should be able to install `@types/node@12` as a workaround.
